project:
  type: website
  output-dir: docs

website: 
  title: Mallory Giesie <br> Environmental Data Scientist
  navbar: 
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Portfolio
      # - href: blog.qmd
      #   text: Blog
      - href: https://bren.ucsb.edu/people/mallory-giesie
        text: About
      - href: Resume/Resume.pdf
        text: Resume
format:
  html:
    theme:
    - mystyles.scss
    toc: true
mainfont: Playfair
editor: visual

