project:
  type: website
  output-dir: docs

website:
  title: "Mallory Giesie"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: blog.qmd
        text: Blog
      - href: Portfolio
        text: Portfolio
format:
  html:
    theme:
    - mystyles.scss
    toc: true

editor: visual

