project:
  type: website
  output-dir: docs

website: 
  title: 
    Mallory Giesie <br> Environmental Data Scientist
  navbar: 
    right:
      - href: index.qmd
        text: Home
      - href: Resume/Resume.pdf
        text: Resume
      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: Portfolio
format:
  html:
    theme:
    - mystyles.scss
    toc: true

editor: visual

