project:
  type: website
  output-dir: docs

website:
  title: "mallorygiesie.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
format:
  html:
    theme: 
    - mystyles.scss
    toc: true

editor: visual

